"""empty message

Revision ID: 25fb549dcc8a
Revises: 84b1859f1695
Create Date: 2020-08-09 16:10:51.277886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fb549dcc8a'
down_revision = '84b1859f1695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentStates', sa.Column('payment_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'paymentStates', 'vaultPayments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paymentStates', type_='foreignkey')
    op.drop_column('paymentStates', 'payment_id')
    # ### end Alembic commands ###
