"""empty message

Revision ID: 6dfac56a4ccc
Revises: 25fb549dcc8a
Create Date: 2020-08-19 21:06:00.600972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfac56a4ccc'
down_revision = '25fb549dcc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('paymentsAmount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'paymentsAmount')
    # ### end Alembic commands ###
