"""empty message

Revision ID: a6d294375c3b
Revises: dcbf14c5959e
Create Date: 2020-08-09 15:17:44.034867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d294375c3b'
down_revision = 'dcbf14c5959e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paymentStates_user_id_fkey', 'paymentStates', type_='foreignkey')
    op.drop_column('paymentStates', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentStates', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('paymentStates_user_id_fkey', 'paymentStates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
