"""empty message

Revision ID: c86cc560d6cb
Revises: 6dfac56a4ccc
Create Date: 2020-09-02 21:48:00.858434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86cc560d6cb'
down_revision = '6dfac56a4ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('usingOAuth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usingOAuth')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
