"""empty message

Revision ID: d2f0a8734534
Revises: a6d294375c3b
Create Date: 2020-08-09 15:23:52.303386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f0a8734534'
down_revision = 'a6d294375c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentStates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentStates',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"paymentStates_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['vaultPayments.id'], name='paymentStates_payment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paymentStates_pkey')
    )
    # ### end Alembic commands ###
